repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.5.12"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.4.16"]
  - repo: https://github.com/tkoyama010/standard-readme-pre-commit
    rev: edcf5d5d60ddb7ad3edb0fbc6c2164fa35e9a8ee
    hooks:
      - id: standard-readme
